# Site settings
title: Carlos Max
header-img: img/home-bg.jpg
email: carlosmax.dev@hotmail.com
copyright_name: Carlos Max
description: "Meu blog"
baseurl: "/"
url: "https://carlosmaxdev.github.io/"
twitter_username: carlosmaxdev
github_username:  carlosmaxdev
facebook_username: 
linkedin_username: carlos-max
email_username:  carlosmax.dev@hotmail.com
disqus_shortname: carlosmaxdev

# Google Analytics
google_tracking_id: UA-102963825-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
